#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="twitterdb")]
	public partial class Database2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void Inserthashtag(hashtag instance);
    partial void Updatehashtag(hashtag instance);
    partial void Deletehashtag(hashtag instance);
    partial void Insertkategoriler(kategoriler instance);
    partial void Updatekategoriler(kategoriler instance);
    partial void Deletekategoriler(kategoriler instance);
    partial void InsertKurum(Kurum instance);
    partial void UpdateKurum(Kurum instance);
    partial void DeleteKurum(Kurum instance);
    partial void Inserttweet(tweet instance);
    partial void Updatetweet(tweet instance);
    partial void Deletetweet(tweet instance);
    #endregion
		
		public Database2DataContext() : 
				base(global::proje.Properties.Settings.Default.twitterdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Database2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Database2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Database2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Database2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<hashtag> hashtags
		{
			get
			{
				return this.GetTable<hashtag>();
			}
		}
		
		public System.Data.Linq.Table<kategoriler> kategorilers
		{
			get
			{
				return this.GetTable<kategoriler>();
			}
		}
		
		public System.Data.Linq.Table<Kurum> Kurums
		{
			get
			{
				return this.GetTable<Kurum>();
			}
		}
		
		public System.Data.Linq.Table<tweet> tweets
		{
			get
			{
				return this.GetTable<tweet>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_id;
		
		private string _admin_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void Onadmin_nameChanging(string value);
    partial void Onadmin_nameChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string admin_name
		{
			get
			{
				return this._admin_name;
			}
			set
			{
				if ((this._admin_name != value))
				{
					this.Onadmin_nameChanging(value);
					this.SendPropertyChanging();
					this._admin_name = value;
					this.SendPropertyChanged("admin_name");
					this.Onadmin_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_id;
		
		private string _Ad;
		
		private string _Soyad;
		
		private System.DateTime _DogumTarihi;
		
		private string _Cinsiyet;
		
		private string _Email;
		
		private string _Telefon;
		
		private string _Adres;
		
		private int _Kurum_id;
		
		private EntityRef<Kurum> _Kurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_idChanging(int value);
    partial void OnUser_idChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnDogumTarihiChanging(System.DateTime value);
    partial void OnDogumTarihiChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnKurum_idChanging(int value);
    partial void OnKurum_idChanged();
    #endregion
		
		public User()
		{
			this._Kurum = default(EntityRef<Kurum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_id
		{
			get
			{
				return this._User_id;
			}
			set
			{
				if ((this._User_id != value))
				{
					this.OnUser_idChanging(value);
					this.SendPropertyChanging();
					this._User_id = value;
					this.SendPropertyChanged("User_id");
					this.OnUser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarihi", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DogumTarihi
		{
			get
			{
				return this._DogumTarihi;
			}
			set
			{
				if ((this._DogumTarihi != value))
				{
					this.OnDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DogumTarihi = value;
					this.SendPropertyChanged("DogumTarihi");
					this.OnDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(11)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kurum_id", DbType="Int NOT NULL")]
		public int Kurum_id
		{
			get
			{
				return this._Kurum_id;
			}
			set
			{
				if ((this._Kurum_id != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKurum_idChanging(value);
					this.SendPropertyChanging();
					this._Kurum_id = value;
					this.SendPropertyChanged("Kurum_id");
					this.OnKurum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_User", Storage="_Kurum", ThisKey="Kurum_id", OtherKey="Kurum_id", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._Kurum_id = value.Kurum_id;
					}
					else
					{
						this._Kurum_id = default(int);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hashtag")]
	public partial class hashtag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hashtag_id;
		
		private string _hashtag_name;
		
		private EntitySet<tweet> _tweets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhashtag_idChanging(int value);
    partial void Onhashtag_idChanged();
    partial void Onhashtag_nameChanging(string value);
    partial void Onhashtag_nameChanged();
    #endregion
		
		public hashtag()
		{
			this._tweets = new EntitySet<tweet>(new Action<tweet>(this.attach_tweets), new Action<tweet>(this.detach_tweets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashtag_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hashtag_id
		{
			get
			{
				return this._hashtag_id;
			}
			set
			{
				if ((this._hashtag_id != value))
				{
					this.Onhashtag_idChanging(value);
					this.SendPropertyChanging();
					this._hashtag_id = value;
					this.SendPropertyChanged("hashtag_id");
					this.Onhashtag_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashtag_name", DbType="NVarChar(140)")]
		public string hashtag_name
		{
			get
			{
				return this._hashtag_name;
			}
			set
			{
				if ((this._hashtag_name != value))
				{
					this.Onhashtag_nameChanging(value);
					this.SendPropertyChanging();
					this._hashtag_name = value;
					this.SendPropertyChanged("hashtag_name");
					this.Onhashtag_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hashtag_tweet", Storage="_tweets", ThisKey="hashtag_id", OtherKey="hashtag_id")]
		public EntitySet<tweet> tweets
		{
			get
			{
				return this._tweets;
			}
			set
			{
				this._tweets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.hashtag = this;
		}
		
		private void detach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.hashtag = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriler")]
	public partial class kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kategori_id;
		
		private System.Nullable<int> _UstK_id;
		
		private string _Kategori_ismi;
		
		private bool _Onay;
		
		private EntitySet<tweet> _tweets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategori_idChanging(int value);
    partial void OnKategori_idChanged();
    partial void OnUstK_idChanging(System.Nullable<int> value);
    partial void OnUstK_idChanged();
    partial void OnKategori_ismiChanging(string value);
    partial void OnKategori_ismiChanged();
    partial void OnOnayChanging(bool value);
    partial void OnOnayChanged();
    #endregion
		
		public kategoriler()
		{
			this._tweets = new EntitySet<tweet>(new Action<tweet>(this.attach_tweets), new Action<tweet>(this.detach_tweets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kategori_id
		{
			get
			{
				return this._Kategori_id;
			}
			set
			{
				if ((this._Kategori_id != value))
				{
					this.OnKategori_idChanging(value);
					this.SendPropertyChanging();
					this._Kategori_id = value;
					this.SendPropertyChanged("Kategori_id");
					this.OnKategori_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UstK_id", DbType="Int")]
		public System.Nullable<int> UstK_id
		{
			get
			{
				return this._UstK_id;
			}
			set
			{
				if ((this._UstK_id != value))
				{
					this.OnUstK_idChanging(value);
					this.SendPropertyChanging();
					this._UstK_id = value;
					this.SendPropertyChanged("UstK_id");
					this.OnUstK_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_ismi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kategori_ismi
		{
			get
			{
				return this._Kategori_ismi;
			}
			set
			{
				if ((this._Kategori_ismi != value))
				{
					this.OnKategori_ismiChanging(value);
					this.SendPropertyChanging();
					this._Kategori_ismi = value;
					this.SendPropertyChanged("Kategori_ismi");
					this.OnKategori_ismiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Bit NOT NULL")]
		public bool Onay
		{
			get
			{
				return this._Onay;
			}
			set
			{
				if ((this._Onay != value))
				{
					this.OnOnayChanging(value);
					this.SendPropertyChanging();
					this._Onay = value;
					this.SendPropertyChanged("Onay");
					this.OnOnayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriler_tweet", Storage="_tweets", ThisKey="Kategori_id", OtherKey="kategori_id")]
		public EntitySet<tweet> tweets
		{
			get
			{
				return this._tweets;
			}
			set
			{
				this._tweets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.kategoriler = this;
		}
		
		private void detach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.kategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kurum")]
	public partial class Kurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kurum_id;
		
		private string _Kurum_name;
		
		private EntitySet<User> _Users;
		
		private EntitySet<tweet> _tweets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKurum_idChanging(int value);
    partial void OnKurum_idChanged();
    partial void OnKurum_nameChanging(string value);
    partial void OnKurum_nameChanged();
    #endregion
		
		public Kurum()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			this._tweets = new EntitySet<tweet>(new Action<tweet>(this.attach_tweets), new Action<tweet>(this.detach_tweets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kurum_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kurum_id
		{
			get
			{
				return this._Kurum_id;
			}
			set
			{
				if ((this._Kurum_id != value))
				{
					this.OnKurum_idChanging(value);
					this.SendPropertyChanging();
					this._Kurum_id = value;
					this.SendPropertyChanged("Kurum_id");
					this.OnKurum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kurum_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kurum_name
		{
			get
			{
				return this._Kurum_name;
			}
			set
			{
				if ((this._Kurum_name != value))
				{
					this.OnKurum_nameChanging(value);
					this.SendPropertyChanging();
					this._Kurum_name = value;
					this.SendPropertyChanged("Kurum_name");
					this.OnKurum_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_User", Storage="_Users", ThisKey="Kurum_id", OtherKey="Kurum_id")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_tweet", Storage="_tweets", ThisKey="Kurum_id", OtherKey="kurum_id")]
		public EntitySet<tweet> tweets
		{
			get
			{
				return this._tweets;
			}
			set
			{
				this._tweets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_tweets(tweet entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tweet")]
	public partial class tweet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tweet_id;
		
		private System.Nullable<int> _kategori_id;
		
		private System.Nullable<int> _user_id;
		
		private string _text;
		
		private System.Nullable<int> _hashtag_id;
		
		private System.Nullable<int> _mod_id;
		
		private string _location;
		
		private string _image_url;
		
		private System.Nullable<int> _kurum_id;
		
		private EntityRef<hashtag> _hashtag;
		
		private EntityRef<kategoriler> _kategoriler;
		
		private EntityRef<Kurum> _Kurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontweet_idChanging(int value);
    partial void Ontweet_idChanged();
    partial void Onkategori_idChanging(System.Nullable<int> value);
    partial void Onkategori_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Onhashtag_idChanging(System.Nullable<int> value);
    partial void Onhashtag_idChanged();
    partial void Onmod_idChanging(System.Nullable<int> value);
    partial void Onmod_idChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Onimage_urlChanging(string value);
    partial void Onimage_urlChanged();
    partial void Onkurum_idChanging(System.Nullable<int> value);
    partial void Onkurum_idChanged();
    #endregion
		
		public tweet()
		{
			this._hashtag = default(EntityRef<hashtag>);
			this._kategoriler = default(EntityRef<kategoriler>);
			this._Kurum = default(EntityRef<Kurum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tweet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tweet_id
		{
			get
			{
				return this._tweet_id;
			}
			set
			{
				if ((this._tweet_id != value))
				{
					this.Ontweet_idChanging(value);
					this.SendPropertyChanging();
					this._tweet_id = value;
					this.SendPropertyChanged("tweet_id");
					this.Ontweet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_id", DbType="Int")]
		public System.Nullable<int> kategori_id
		{
			get
			{
				return this._kategori_id;
			}
			set
			{
				if ((this._kategori_id != value))
				{
					if (this._kategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkategori_idChanging(value);
					this.SendPropertyChanging();
					this._kategori_id = value;
					this.SendPropertyChanged("kategori_id");
					this.Onkategori_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(140)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashtag_id", DbType="Int")]
		public System.Nullable<int> hashtag_id
		{
			get
			{
				return this._hashtag_id;
			}
			set
			{
				if ((this._hashtag_id != value))
				{
					if (this._hashtag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhashtag_idChanging(value);
					this.SendPropertyChanging();
					this._hashtag_id = value;
					this.SendPropertyChanged("hashtag_id");
					this.Onhashtag_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_id", DbType="Int")]
		public System.Nullable<int> mod_id
		{
			get
			{
				return this._mod_id;
			}
			set
			{
				if ((this._mod_id != value))
				{
					this.Onmod_idChanging(value);
					this.SendPropertyChanging();
					this._mod_id = value;
					this.SendPropertyChanged("mod_id");
					this.Onmod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_url", DbType="NVarChar(MAX)")]
		public string image_url
		{
			get
			{
				return this._image_url;
			}
			set
			{
				if ((this._image_url != value))
				{
					this.Onimage_urlChanging(value);
					this.SendPropertyChanging();
					this._image_url = value;
					this.SendPropertyChanged("image_url");
					this.Onimage_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurum_id", DbType="Int")]
		public System.Nullable<int> kurum_id
		{
			get
			{
				return this._kurum_id;
			}
			set
			{
				if ((this._kurum_id != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkurum_idChanging(value);
					this.SendPropertyChanging();
					this._kurum_id = value;
					this.SendPropertyChanged("kurum_id");
					this.Onkurum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hashtag_tweet", Storage="_hashtag", ThisKey="hashtag_id", OtherKey="hashtag_id", IsForeignKey=true)]
		public hashtag hashtag
		{
			get
			{
				return this._hashtag.Entity;
			}
			set
			{
				hashtag previousValue = this._hashtag.Entity;
				if (((previousValue != value) 
							|| (this._hashtag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hashtag.Entity = null;
						previousValue.tweets.Remove(this);
					}
					this._hashtag.Entity = value;
					if ((value != null))
					{
						value.tweets.Add(this);
						this._hashtag_id = value.hashtag_id;
					}
					else
					{
						this._hashtag_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("hashtag");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriler_tweet", Storage="_kategoriler", ThisKey="kategori_id", OtherKey="Kategori_id", IsForeignKey=true)]
		public kategoriler kategoriler
		{
			get
			{
				return this._kategoriler.Entity;
			}
			set
			{
				kategoriler previousValue = this._kategoriler.Entity;
				if (((previousValue != value) 
							|| (this._kategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriler.Entity = null;
						previousValue.tweets.Remove(this);
					}
					this._kategoriler.Entity = value;
					if ((value != null))
					{
						value.tweets.Add(this);
						this._kategori_id = value.Kategori_id;
					}
					else
					{
						this._kategori_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("kategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_tweet", Storage="_Kurum", ThisKey="kurum_id", OtherKey="Kurum_id", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.tweets.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.tweets.Add(this);
						this._kurum_id = value.Kurum_id;
					}
					else
					{
						this._kurum_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
